const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');
const { getStore } = require('@netlify/blobs');

function loadAvailability() {
  try {
    const file = path.join(process.cwd(), '_data', 'availability.yml');
    return yaml.load(fs.readFileSync(file, 'utf8'));
  } catch {
    return {
      timezone: 'America/New_York',
      slot_duration_minutes: 20,
      booking_notification_email: process.env.BOOKING_NOTIFICATION_EMAIL,
    };
  }
}

// Slot key format: "YYYY-MM-DDTHH:MM" (Eastern time, as generated by get-slots)
function formatSlotForEmail(slot, timezone) {
  const [datePart, timePart] = slot.split('T');
  // Build a display-safe date using noon UTC so date boundaries don't shift
  const d = new Date(`${datePart}T12:00:00Z`);
  const dateFmt = new Intl.DateTimeFormat('en-US', {
    timeZone: 'UTC',
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  }).format(d);
  const [h, m] = timePart.split(':').map(Number);
  const period = h >= 12 ? 'PM' : 'AM';
  const displayH = h === 0 ? 12 : h > 12 ? h - 12 : h;
  const timeFmt = `${displayH}:${String(m).padStart(2, '0')} ${period}`;
  const tzLabel = timezone === 'America/New_York' ? 'ET' : timezone;
  return `${dateFmt} at ${timeFmt} ${tzLabel}`;
}

async function sendEmail({ to, subject, html, replyTo }) {
  const from = process.env.RESEND_FROM_EMAIL || 'Bronte Advisory <bookings@bronteadvisory.com>';
  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ from, to: [to], subject, html, reply_to: replyTo }),
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Resend error ${res.status}: ${body}`);
  }
}

exports.handler = async function (event) {
  const headers = {
    'Access-Control-Allow-Origin': '*',
    'Content-Type': 'application/json',
  };

  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 204, headers };
  }

  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, headers, body: JSON.stringify({ error: 'Method not allowed' }) };
  }

  let body;
  try {
    body = JSON.parse(event.body);
  } catch {
    return { statusCode: 400, headers, body: JSON.stringify({ error: 'Invalid request body' }) };
  }

  const { slot, firstName, lastName, email, role, message } = body;
  if (!slot || !firstName || !lastName || !email) {
    return { statusCode: 400, headers, body: JSON.stringify({ error: 'Missing required fields' }) };
  }

  // Basic slot format validation: YYYY-MM-DDTHH:MM
  if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(slot)) {
    return { statusCode: 400, headers, body: JSON.stringify({ error: 'Invalid slot format' }) };
  }

  try {
    const store = getStore({ name: 'bookings', consistency: 'strong' });

    // Atomic check-and-set: if the key already exists the slot is taken
    const existing = await store.get(slot);
    if (existing) {
      return {
        statusCode: 409,
        headers,
        body: JSON.stringify({ error: 'This slot has just been taken. Please choose another time.' }),
      };
    }

    const av = loadAvailability();
    const bookingData = {
      firstName,
      lastName,
      email,
      role: role || '',
      message: message || '',
      bookedAt: new Date().toISOString(),
    };
    await store.set(slot, JSON.stringify(bookingData));

    const notifyEmail =
      av.booking_notification_email || process.env.BOOKING_NOTIFICATION_EMAIL;
    const slotDisplay = formatSlotForEmail(slot, av.timezone);
    const duration = av.slot_duration_minutes || 20;

    // Notify Dr. Bronte
    if (notifyEmail && process.env.RESEND_API_KEY) {
      await sendEmail({
        to: notifyEmail,
        subject: `New Clarity Call — ${firstName} ${lastName}`,
        replyTo: email,
        html: `
          <div style="font-family:sans-serif;max-width:520px;">
            <h2 style="color:#1F6F8B;">New Clarity Call Booking</h2>
            <p><strong>Date:</strong> ${slotDisplay}</p>
            <p><strong>Duration:</strong> ${duration} minutes · via Zoom</p>
            <hr style="border-color:#E4D8DC;margin:16px 0;"/>
            <p><strong>Name:</strong> ${firstName} ${lastName}</p>
            <p><strong>Email:</strong> <a href="mailto:${email}">${email}</a></p>
            <p><strong>Role / Industry:</strong> ${role || '—'}</p>
            <p><strong>Message:</strong></p>
            <blockquote style="border-left:3px solid #3DBCC4;padding-left:12px;color:#444;">
              ${(message || '—').replace(/\n/g, '<br>')}
            </blockquote>
            <p style="color:#999;font-size:12px;margin-top:24px;">
              Reply to this email to respond directly to ${firstName}.
            </p>
          </div>
        `,
      });
    }

    // Confirm to visitor
    if (process.env.RESEND_API_KEY) {
      await sendEmail({
        to: email,
        subject: 'Your Clarity Call with Dr. Lizzie Bronte is Confirmed',
        replyTo: notifyEmail,
        html: `
          <div style="font-family:sans-serif;max-width:520px;">
            <h2 style="color:#1F6F8B;">Your Clarity Call is Confirmed</h2>
            <p>Hi ${firstName},</p>
            <p>Your ${duration}-minute Clarity Call with Dr. Lizzie Bronte is confirmed for:</p>
            <p style="font-size:18px;font-weight:bold;color:#1F6F8B;">${slotDisplay}</p>
            <p>This call will be via Zoom. Dr. Bronte will send you the link shortly before your call.</p>
            <p>Questions? Simply reply to this email.</p>
            <br/>
            <p style="color:#444;">
              Warm regards,<br/>
              <strong>Dr. Lizzie Bronte</strong><br/>
              Bronte Advisory
            </p>
          </div>
        `,
      });
    }

    return {
      statusCode: 200,
      headers,
      body: JSON.stringify({ success: true, slotDisplay }),
    };
  } catch (err) {
    console.error('create-booking error:', err);
    return {
      statusCode: 500,
      headers,
      body: JSON.stringify({ error: 'Something went wrong. Please try again or email us directly.' }),
    };
  }
};
